## NumPy

### Creating Arrays

In [20]:
import numpy as np

#0D array
arr0 = np.array(45)

print(arr0)
print(type(arr0))

#1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

#2D array
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

#3D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

#We can also check the number of dimensions
print(arr0.ndim)
print(arr3.ndim)

#When creating an array, we can define the number of dimensions it has
arr4 = np.array([1,2,3], ndmin=5)
print(arr4)


45
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 3 5]
 [2 4 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
3
[[[[[1 2 3]]]]]


### Array Creation using Functions

In [ ]:
arr5 = np.zeros((2,1)) #tuple of rows, columns - known as shape
print(arr5) #we can use to initialize an empty matrix b4 filling it with values

arr6 = np.ones((2,2)) #same as zeros
print(arr6) #often used in ML as test matrices

arr7 = np.empty((2,3)) #same as above
print(arr7) #contains random leftover values from memory. faster than above 2 funcs

arr8 = np.arange(2,10,2) #same as normal range func
print(arr8)

arr9 = np.linspace(0,10,5) #creates an array of n(5) numbers between 0 and 10 (inclusive)
print(arr9)

arr10 = np.eye(3) #creates an identity matrix of n number of rows
print(arr10)

arr11 = np.random.rand(2) #(shape) 
print(arr11) #creates random values of given shape

arr12 = np.random.randint(2,12,(2,2))
print(arr12) #creates random values between given range of given shape

[[0.]
 [0.]]
[[1. 1.]
 [1. 1.]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.22192398 0.34057042]
[[ 7 10]
 [ 6  3]]


### Accessing Array Elements

It is the same as lists, but instead of doing list[1][2] for nested lists, we do arr[1, 2] in numpy

### Array Slicing 

It is also the same as list slicing but a bit different when it comes to nested arrays

In [40]:
#1st number is to access the nested array(s), 2nd is to slice
print(arr2[1, 1:4]) #nested array [1] slice 1:4
print(arr2[0:2, 0:4]) #slice 0:4 in all nested arrays of index 0 and 1 
print(arr2[0:2, 2]) #return index 2 element from both nested arrays
arr2.shape


[4 6]
[[1 3 5]
 [2 4 6]]
[5 6]


(2, 3)