## NumPy

### Creating Arrays

In [9]:
import numpy as np

#0D array
arr0 = np.array(45)

print(arr0)
print(type(arr0))

#1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

#2D array
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

#3D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

#We can also check the number of dimensions
print(arr0.ndim)
print(arr3.ndim)

#When creating an array, we can define the number of dimensions it has
arr4 = np.array([1,2,3], ndmin=5)
print(arr4)

45
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 3 5]
 [2 4 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
3
[[[[[1 2 3]]]]]


### Accessing Array Elements

It is the same as lists, but instead of doing list[1][2] for nested lists, we do arr[1, 2] in numpy

### Array Slicing 

It is also the same as list slicing but a bit different when it comes to nested arrays

In [ ]:
#1st number is to access the nested array(s), 2nd is to slice
print(arr2[1, 1:4]) #nested array [1] slice 1:4
print(arr2[0:2, 0:4]) #slice 0:4 in all nested arrays of index 0 and 1 
print(arr2[0:2, 2]) #return index 2 element from both nested arrays


[4 6]
[[1 3 5]
 [2 4 6]]
