## NumPy

### Creating Arrays

In [2]:
import numpy as np

#0D array
arr0 = np.array(45)

print(arr0)
print(type(arr0))

#1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

#2D array
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

#3D array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

#When creating an array, we can define the number of dimensions it has
arr4 = np.array([1,2,3], ndmin=5)
print(arr4)


45
<class 'numpy.ndarray'>
[1 2 3 4 5]
[[1 3 5]
 [2 4 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[[[1 2 3]]]]]


### Array Creation using Functions

In [3]:
arr5 = np.zeros((2,1)) #tuple of rows, columns - known as shape
print(arr5) #we can use to initialize an empty matrix b4 filling it with values

arr6 = np.ones((2,2)) #same as zeros
print(arr6) #often used in ML as test matrices

arr7 = np.empty((2,3)) #same as above
print(arr7) #contains random leftover (uninitialized) values from memory. faster than above 2 funcs

arr8 = np.arange(2,10,2) #same as normal range func
print(arr8)

arr9 = np.linspace(0,10,5) #creates an array of n(5) numbers between 0 and 10 (inclusive)
print(arr9)

arr10 = np.eye(3) #creates an identity matrix of n number of rows
print(arr10)

arr11 = np.random.rand(2) #(shape) 
print(arr11) #creates random values of given shape

arr12 = np.random.randint(2,12,(2,2))
print(arr12) #creates random values between given range of given shape

[[0.]
 [0.]]
[[1. 1.]
 [1. 1.]]
[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.98564478 0.752362  ]
[[10  7]
 [10  8]]


### Accessing Array Elements

It is the same as lists, but instead of doing list[1][2] for nested lists, we do arr[1, 2] in numpy

### Array Slicing 

It is also the same as list slicing but a bit different when it comes to nested arrays

In [4]:
#1st number is to access the nested array(s), 2nd is to slice
print(arr2[1, 1:4]) #nested array [1] slice 1:4
print(arr2[0:2, 0:4]) #slice 0:4 in all nested arrays of index 0 and 1 
print(arr2[0:2, 2]) #return index 2 element from both nested arrays


[4 6]
[[1 3 5]
 [2 4 6]]
[5 6]


### Array Operations

Arithmetic: +, -, *, / <br>
Works with: <br>
~ same shape <br>
~ broadcasting

Scalar <br>
E.g - a + 5 <br>
b * 10 <br>
Applies to all elements

### Shape Manipulation

In [5]:
arr16 = np.array([[1,2],[3,4]])
print(arr16.reshape(2,1,2))
print(arr16.flatten()) #make it 1D
#or
print(arr16.reshape(-1))
print(arr16.T) #Transpose (swap rows and columns)
print(arr16.shape) #returns dimensions (rows, columns)
print(arr16.ndim) #returns just normal dimension

[[[1 2]]

 [[3 4]]]
[1 2 3 4]
[1 2 3 4]
[[1 3]
 [2 4]]
(2, 2)
2


### Aggregate Operations

In [6]:
arr13 = [[1,2,3],[4,5,6]]
print(np.sum(arr13))
print(np.mean(arr13))
print(np.min(arr13))
print(np.max(arr13))
print(np.var(arr13)) #variance - how much data spreads from the mean
print(np.std(arr13)) #root of variance

print(np.sum(arr13, axis=0)) #column-wise
print(np.sum(arr13, axis=1)) #row-wise

21
3.5
1
6
2.9166666666666665
1.707825127659933
[5 7 9]
[ 6 15]


### Element-wise Functions

In [7]:
print(np.sqrt(arr13))
print(np.exp(arr13)) #e raised to the power of each element
print(np.log(arr13)) #ln (element) aka log base e
print(np.abs(arr13)) #absolute value

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1 2 3]
 [4 5 6]]


### Comparison Operators

In [8]:
arr14 = np.array([1,2,3,4])
print(arr14>1)
print(arr14 == 3)
print(arr14<4)
print(arr14 < arr8)
#this also uses broadcasting and compares element w element

#we can even do boolean indexing such as:
print(arr14[arr14>3]) #to get actual values instead of boolean


[False  True  True  True]
[False False  True False]
[ True  True  True False]
[ True  True  True  True]
[4]


### Logical Operators

In [9]:
print(np.logical_and(arr14 > 4, arr14 <5))
print(np.logical_or(arr14 > 4, arr14 <5))
print(np.logical_not(arr14<3))
print(np.logical_xor(arr14<2, arr14>3)) #T if different else F


[False False False False]
[ True  True  True  True]
[False False  True  True]
[ True False False  True]


### Matrix Multiplication

In [10]:
#this is different from multiplying 2 arrays like a*b (element-wise)

arr15 = np.array([[5,7],[4,6],[8,9]])
print(np.dot(arr13, arr15))
#or
print(arr13@arr15)


[[ 37  46]
 [ 88 112]]
[[ 37  46]
 [ 88 112]]
